# Generated by Django 5.1.4 on 2025-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='homes',
            field=models.ManyToManyField(to='main_app.home'),
        ),
    ]
